const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const TABLE_SIZE = 'TABLE_SIZE';

//USER
const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT';
const SIGNUP = 'SIGNUP';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_REDIRECT = 'SIGNUP_REDIRECT';
//SlIDER
const SPINNER_ON = 'SlLIDER_ON';
const SPINNER_OFF = 'SLIDER_OFF';
// USERS PAGE
const WAIT_FOR_RESPONSE = 'WAIT_FOR_RESPONSE';
const SET_USERS_DATA = 'SET_USERS_DATA';
const REQUEST_ERROR = 'REQUEST_ERROR';
const USER_TABLE_SELECT_ROW = 'USER_TABLE_SELECT_ROW';
const CREATE_NEW_USER = 'CREATE_NEW_USER';
const EDIT_USER = 'EDIT_USER';
const USER_CARD_CLOSE = 'USER_CARD_CLOSE';
const USER_TABLE_CLEAR_SELECT_LIST = 'USER_TABLE_CLEAR_SELECT_LIST';
// USER CARD
const USER_CARD_SAVE = 'USER_CARD_SAVE';

export default {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  OPEN_MODAL,
  CLOSE_MODAL,
  TABLE_SIZE,
  SPINNER_OFF,
  SPINNER_ON,
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_REDIRECT,
  WAIT_FOR_RESPONSE,
  SET_USERS_DATA,
  REQUEST_ERROR,
  USER_TABLE_SELECT_ROW,
  CREATE_NEW_USER,
  EDIT_USER,
  USER_CARD_CLOSE,
  USER_CARD_SAVE,
  USER_TABLE_CLEAR_SELECT_LIST
};
