const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
//USER
const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT';
const SIGNUP = 'SIGNUP';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_REDIRECT = 'SIGNUP_REDIRECT';
// USERS PAGE
const WAIT_FOR_RESPONSE = 'WAIT_FOR_RESPONSE';
const SET_USERS_DATA = 'SET_USERS_DATA';
const REQUEST_ERROR = 'REQUEST_ERROR';
const USERS_TABLE_SELECT_ROW = 'USER_TABLE_SELECT_ROW';
const CREATE_NEW_USER = 'CREATE_NEW_USER';
const EDIT_USER = 'EDIT_USER';
const USER_CARD_CLOSE = 'USER_CARD_CLOSE';
const USERS_TABLE_CLEAR_SELECT_LIST = 'USER_TABLE_CLEAR_SELECT_LIST';
const USERS_STATS_REQUEST = 'USERS_STATS_REQUEST';
const USERS_STATS_SHOW = 'USER_STATS_SHOW';
const USERS_STATS_SHOW_ERROR = 'USER_STATS_SHOW_ERROR';
const USERS_TABLE_SIZE = 'SET_USER_TABLE_SIZE';
const USERS_TABLE_PAGE = 'USER_TABLE_PAGE';

// USER CARD
const USER_CARD_SAVE = 'USER_CARD_SAVE';
const USER_CARD_SUBMIT = 'USER_CARD_SUBMIT';
export default {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  OPEN_MODAL,
  CLOSE_MODAL,
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_REDIRECT,
  WAIT_FOR_RESPONSE,
  SET_USERS_DATA,
  REQUEST_ERROR,
  USERS_TABLE_SELECT_ROW,
  CREATE_NEW_USER,
  EDIT_USER,
  USER_CARD_CLOSE,
  USER_CARD_SAVE,
  USERS_TABLE_CLEAR_SELECT_LIST,
  USERS_STATS_REQUEST,
  USERS_STATS_SHOW,
  USERS_STATS_SHOW_ERROR,
  USERS_TABLE_SIZE,
  USERS_TABLE_PAGE,
  USER_CARD_SUBMIT
};
