const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'
const TABLE_SIZE = 'TABLE_SIZE'
const USER_IS_LOGINED = 'USER_IS_LOGINED'
const USER_IS_OUT = 'USER_IS_OUT'
const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const SET_USER_DATA = 'SET_USER_DATA'
const SHOW_FORM_MESSAGE = 'SHOW_FORM_MESSAGE'
const HIDE_FORM_MESSAGE = 'HIDE_FORM_MESSAGE'

export default {
  OPEN_MODAL,
  HIDE_FORM_MESSAGE,
  SHOW_FORM_MESSAGE,
  CLOSE_MODAL,
  TABLE_SIZE,
  USER_IS_LOGINED,
  USER_IS_OUT,
  USER_LOGIN_REQUEST,
  SET_USER_DATA
}
